apps:
  chat_app:
    url: chat
    dev:
      allowed_origins: localhost:8080
      write_buffer_size: 1024
      read_buffer_size: 1024
    prod:
      allowed_origins: localhost:8080
      write_buffer_size: 1024
      read_buffer_size: 1024
